# Generated by Django 4.2.8 on 2023-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_room_delete_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feats', models.JSONField()),
                ('equipment', models.JSONField()),
                ('pouch', models.JSONField()),
                ('player', models.CharField(max_length=100)),
                ('hp_current', models.IntegerField()),
                ('hp_max', models.IntegerField()),
            ],
        ),
    ]
