# Generated by Django 4.2.5 on 2023-12-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='player',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='player',
            name='feats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pouch',
        ),
    ]
