# Generated by Django 4.2.5 on 2024-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_room_remove_player_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
